### ISSUE TITLE
hamiltonian-simulation is throwing the error

### ISSUE THREAD

**Issue by manu123416** [SRI-International/QC-App-Oriented-Benchmarks#128]
Hi, I tried running the hamiltonian-simulation code in the pycharm. I am getting the below error:
![image](https://user-images.githubusercontent.com/95257431/177919219-05a1c649-03b4-4962-960b-34209866747f.png)
The directory structure of my program looks as below:
![image](https://user-images.githubusercontent.com/95257431/177919338-29130385-9f5b-4a68-851c-b74747fa81ff.png)
Please give suggestion on how to resolve this error?

**Comment by manu123416** [comment]
There is one question which came across after reading the paper. The formula for the creating the volumetric background is as below:
![image](https://user-images.githubusercontent.com/95257431/178041090-53a8beb3-aec6-485e-806f-30acf1b0b6c8.png)
I am not able to understand what values of depth I should I put in the formula?
![image](https://user-images.githubusercontent.com/95257431/178041511-54ba1192-57b5-49f0-9a1d-e064c0d9a877.png)
Suppose, If I put w=11 and d= 15, my calculation shows that this square box should be white. So, I think, I am not understanding the depth definition in your paper correctly? If possible, please explain a little so that formula satisfied the calculations?

**Comment by rtvuser1** [comment]
In the formula you are citing, the 'd' represents the un-tranpiled depth of
the circuit.  What you see in the volumetric plot you clipped is the
transpiled depth, using a basis chosen for 'normalizatiion' purposes (to be
able to compare results across machines).  The transpiled depth is about
12X the un-transpiled.  So the 15 would actually be 12X15 = 180 on the
volumetric plot, which would be in the white area.
