### ISSUE TITLE
Problem in executing the vqe code

### ISSUE THREAD

**Issue by manu123416** [SRI-International/QC-App-Oriented-Benchmarks#131]
Hello Sir,
I am finding problem in executing the vqe code.
The error I am getting is below:
![image](https://user-images.githubusercontent.com/95257431/178116297-e8729437-9d9e-4002-93c6-04419842406a.png)
I tried installing these packages but the error is still not resolved.
Need your help.

**Comment by rtvuser1** [comment]
I only see a snapshot of the top of the .py file, there is no error message to review.  Can you send error message.

Note: there are no additional packages to install.  the "opflow"  functions are all part of the general qiskit install.
I don't believe anything special is needed to execute the vqe ansatz benchmark.

Since I cannot see the error message yet, I cannot comment on what you are running into ...

**Comment by manu123416** [comment]
The error I am getting is:
![image](https://user-images.githubusercontent.com/95257431/178131102-8bdf09dc-b880-41fe-8966-e1b06e366299.png)
I think, there is some problem with the packages.

**Comment by rtvuser1** [comment]
As of Qiskit verion 0.26, the qiskit.opflow module is a part of the standard Qiskit install.  It used to be part of qiskit_aqua I believe, but for at least a year it has been moved to the primary qiskit install, so you don't need any other installs.
And you shouldn't need to edit anything in the code for the benchmarks.

It is possible you have an older installation of qiskit.  If you put the following into a python file and execute it you can see all your latest versions of several qiskit modules:

import qiskit
qiskit.__qiskit_version__

I have the latest, and the output I get is:
{'qiskit-terra': '0.20.2', 'qiskit-aer': '0.10.4', 'qiskit-ignis': '0.7.1', 'qiskit-ibmq-provider': '0.19.1', 'qiskit-aqua': None, 'qiskit': '0.36.2', 'qiskit-nature': '0.4.1', 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

'qiskit' itself is up to 0.36.2 (or maybe even greater by now)

If yours is less than 0.26, that would the the issue.  You will need to upgrade your qiskit installation.

**Comment by manu123416** [comment]
![image](https://user-images.githubusercontent.com/95257431/178190105-e4742549-4f2d-4522-ae57-a7eda8281d7a.png)
Yes, my qiskit version is old. Thank you for this great help. 
Do you know how to upgrade the qiskit installation?

**Comment by manu123416** [comment]
Thank you for the great help. Problem resolved.
