### ISSUE TITLE
Allowing for one-click access and minimal environment setup with qBraid

### ISSUE THREAD

**Issue by rryoung98** [SRI-International/QC-App-Oriented-Benchmarks#447]
Hello,  I'd like to suggest adding a feature that is similar to Binder, where users will be able to launch the benchmarking notebooks and have pre-made python environments for running the notebooks as well. It only requires adding the launch on qbraid button in the following PR: https://github.com/SRI-International/QC-App-Oriented-Benchmarks/pull/446 and users can select the QED-C benchmarking environments for the respective software frameworks such as cirq, qiskit, etc that is freely available on qbraid.

**Comment by rtvuser1** [comment]
Closed, as the README was enhanced to reference qBraid

**Comment by rtvuser1** [comment]
Closed , as the README was enhanced to reference qBraid
