### ISSUE TITLE
qiskit v1 broke functionality

### ISSUE THREAD

**Issue by ashterenli** [SRI-International/QC-App-Oriented-Benchmarks#457]
qiskit 1.0 does not have `execute()`:

https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0

```
Qiskit’s execute() function is removed.
This function served as a high-level wrapper around transpiling a circuit
with some transpile options and running it on a backend with some run options.
To do the same thing, you can explicitly use the [transpile()]
(https://docs.quantum.ibm.com/api/qiskit/compiler#qiskit.compiler.transpile)
function (with appropriate transpile options)
 followed by backend.run() (with appropriate run options).
```

However, `_common/qiskit/execute.py` deliberately uses `execute()` instead of `run()`:

```
 706                 ''' some circuits, like Grover's behave incorrectly if we use run()
 707                 job = backend.run(simulation_circuits, shots=shots,
 708                     noise_model=this_noise, basis_gates=this_noise.basis_gates,
 709                     **backend_exec_options_copy)
 710                 '''   
 711                 job = execute(simulation_circuits, backend, shots=shots,
 712                     noise_model=this_noise, basis_gates=this_noise.basis_gates,
 713                     **backend_exec_options_copy)
```

I wonder what is the way forward with qiskit 1.0?

**Comment by rtvuser1** [comment]
Investigating this now ...

**Comment by rtvuser1** [comment]
Changes have been made to the code to support Qiskit 1.0, partially so far, and currently reside in a branch named: **upgrade-to-qiskit-1.0**
Note that the **vqe** benchmark has not been upgraded yet to address the removal of opflow. 
However, all the other basic benchmarks appear to work with these changes.
Continued testing will likely reveal additional changes required before merging to master.

**Comment by rtvuser1** [comment]
Closing this Issue as all 1.0 changes have been merged to master.  
One exception: the image-recognition benchmark fails with 1.0.  This will be discussed in a separate issue.
