### ISSUE TITLE
[new feature] Add possibility of multiple transpilation passes in Qiskit

### ISSUE THREAD

**Issue by miamico** [SRI-International/QC-App-Oriented-Benchmarks#51]
The transpiler in Qiskit may output circuits with different depths after the transpilation pass. To get the best performance out of the transpiler it is recommended to transpile a circuit multiple times and pick the shortest circuit (for example in cx count)

**Comment by japanavi** [comment]
Implemented and merged in this [Pull Request](https://github.com/SRI-International/QC-App-Oriented-Benchmarks/pull/93)
