### ISSUE TITLE
Figure 9 from paper does not use proper depth

### ISSUE THREAD

**Issue by nonhermitian** [SRI-International/QC-App-Oriented-Benchmarks#7]
In the paper https://arxiv.org/abs/2110.03137 it is said that the depth calculation for circuits is done using the basis set `['rx', 'ry', 'rz', 'cx']`.  However when looking at Fig 9 of the paper the reported depth does not match what the depth is when the circuit is decomposed to the indicated basis.  Namely the routine just does a decompose 

https://github.com/SRI-International/QC-App-Oriented-Benchmarks/blob/5e1f68eed96d667b9bcc08d3b04b2004f4c04643/quantum-fourier-transform/qiskit/qft_benchmark.py#L313

before passing on to execute that computes the depth of this decomposition:

https://github.com/SRI-International/QC-App-Oriented-Benchmarks/blob/5e1f68eed96d667b9bcc08d3b04b2004f4c04643/_common/qiskit/execute.py#L237

This does not decompose to the correct basis, and the circuits are much shorter than they should be. At 7 qubits, the decomposed depth is 31, which matches Fig 9., but the actual depth with the correct basis is 78.  The same is true for the circuits that are swap mapped to the Casablanca system, where I get an avg depth of 117.

**Comment by rtvuser1** [comment]
Closed after clarification on the explanation in the paper
